export const PROJECT_REQUIRED = 'Project value required.';
export const EXPENSE_REQUIRED = 'Please select expense details.';
export const BILL_REQUIRED = 'Bill number required.';
export const CASH_MEMO_REQUIRED = 'Cash Memo number required.';
export const BILL_MATCHED = 'Bill number can not be same as previous ones.';
export const AMOUNT_REQUIRED = 'Amount required.';
export const AMOUNT_NOT_VALID = 'Amount should be numeric and greater than zero.';
export const BAL_NOT_SUFFICIENT = 'Your balance amount is not sufficient.';
export const PARTICULAR_REQUIRED = 'Particulars required.';
export const PHONE_REQUIRED = 'Phone number required.';
export const PURPOSE_REQUIRED = 'Please select purpose.';
export const SUBMIT_TO_TYPES = ['Supervisor', 'FSO'];
export const SUBMIT_TO_UK_TYPES = ['Supervisor'];
export const SUBMIT_TO_IND_TYPES = ['Supervisor']
export const SUBMIT_TO_VDH = ['VDH']
export const SUBMIT_TO_HR = ['HR']
export const SUBMIT_TO_FSO = ['FSO']
export const TOTAL_VOUCHERS = 'Number of Vouchers';
export const TOTAL_AMOUNT = 'Total Amount';
export const MOBILE_INSTRUCTIONS = 'Mobile phone reimbursement can be claimed only once for a month and for one mobile no. only';
export const PETROL_INSTRUCTIONS = 'NOTE : Please submit the petrol claim for bills pertaining to current financial year only';
export const DRIVER_INSTRUCTIONS = 'I hereby declare that I have paid the salary to my driver as per claim details given below.';
