
import Config from '../config/index';
const BASE_URL = Config.api.host;
const CAREER_BASE_URL = Config.api.careerHost;
const AD_LOGOUT_BASE_URL = Config.api.adLogOut;
const initialURL = BASE_URL + 'ntlessnet/webservices/';
const recruitmentURL = CAREER_BASE_URL + 'RecruitmentQA/Recruitment/';
const recruitmentPostDevUrl = CAREER_BASE_URL + 'Careers/Recruitment/';
const ISD_BASE_URL = BASE_URL + 'ess2/ISD/ISD/';
const COMMON_VOUCHER_BASE_URL = BASE_URL + 'ess2/VoucherSystem/';
const VOUCHER_BASE_URL = BASE_URL + 'ess2/VoucherSystem/ActionHandler/';
const VOUCHER_OLD_BASE_URL = BASE_URL + 'ess2/VoucherSystem/ActionHandler/';
const TIMESHEET_BASE_URL = BASE_URL + 'ess2/Timesheet/TimesheetHandler/';
export default {
    'isDevEnvironment': BASE_URL.includes('dev') ? true : false,
    'checkEligibility':BASE_URL + 'ess2/Misc/Attendence/ViewAttendence',
    'checkAttendance':BASE_URL + 'ess2/Misc/Attendence/MarkAttendenceMobile',
    'getAppVersion':BASE_URL + 'ess2/CommonHandler/GetAppVersion',
    'loginUrl': initialURL + 'Authentication.asmx/AuthenticateUser?',
    'loginNewUrl': initialURL + 'Authentication.asmx/AuthenticateUserapp?',
    'loginNewUrl2': BASE_URL + 'ess2/CommonHandler/AuthenticateUserAppWithToken',
    'pendingRequestUrl': recruitmentURL + 'RecruitmentHome/GetPendingForApproval?',
    'getSupervisorListUrl': recruitmentURL + 'Common/GetRequestorBasedonparam?',
    'updateRequestStatusUrl': recruitmentURL + 'Request/UpdateStatus?',
    'pendingRequestPostURL': recruitmentPostDevUrl + 'RecruitmentHome/GetPendingForApproval?',
    'getPendingDashboardCountUrl': BASE_URL + 'ess2/misc/WebAPI/GetPendingCount',
    'getRequestorListUrl': recruitmentPostDevUrl + 'Common/GetRequestorBasedonparam?',
    'voucherActionUrl': BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/VoucherAction',
    'RRActionUrl': recruitmentPostDevUrl + 'Request/UpdateRequestStatus',
    'getLCVoucherUrl': BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/GetLCVVoucherDetails',
    'getCSHVoucherUrl': BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/GetCSHVoucherDetails',
    'pendingVoucherPostURL' : BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/GetVouchersPendingForApproval',
    'fetchSuperVisorListUrl': CAREER_BASE_URL + 'Careers/Recruitment/Common/GetRequestorBasedonparam?', //all employee data
    'cancelActionUrl': BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/VoucherAction',
    'approveActionUrl': CAREER_BASE_URL + 'Careers/Recruitment/Request/UpdateRequestStatus',
    'getCshVouchers': BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/GetCSHVoucherDetails',
    'getLcvVouchers': BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/GetLCVVoucherDetails',
    'getTrPendingList':BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/GetTRPendingForApproval',
    'trActions':BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/TRActions',
    'getTrApproverList':BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/GetApproversList',
    'getHRCommunication':BASE_URL + 'ess2/misc/Myinfo/HRCommunication',
    'getGratuityDetails':BASE_URL + 'ess2/misc/Myinfo/GetBalances',
    'addressInfoUrl' : BASE_URL + 'ess2/misc/Myinfo/GetAddressDetailsSap',
    'getFamily':BASE_URL + 'ess2/misc/Myinfo/GetFamilyDetailsSap',
    'getYearLocation':BASE_URL + 'ess2/misc/Myinfo/GetYearNCountry',
    'getHolidays':BASE_URL + 'ess2/misc/Myinfo/GetHolidayList',
    'getLeaves':BASE_URL + 'ess2/Leave/Leave/GetPendingLeaveList',
    'submitLeaveRequest':BASE_URL + 'ess2/Leave/Leave/LeaveAction',
    'usVoucherActionUrl': BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/USVoucherActions',
    'getVisaUrl': BASE_URL + 'ess2/Visa/VisaHandler/GetMyTask',
    'visaActionUrl': BASE_URL + 'ess2/Visa/VisaHandler/submitVisaDetails',
    'visaHistoryUrl': BASE_URL + 'ess2/Visa/VisaHandler/GetHistory',
    'getVisitingUrl': BASE_URL + 'ess2/VisitingCard/VisitingCard/GetAllRequest',
    'visitingActionUrl': BASE_URL + 'ess2/VisitingCard/VisitingCard/UpdateVisitingCardRequest',
    'fetchSupervisorVisaUrl' : BASE_URL + 'ess2/Visa/VisaHandler/SearchEmpData',
    'createLeave':BASE_URL + 'ess2/Leave/Leave/LeaveBalances',
    'getECRPUrl': BASE_URL + 'ess2/CRP/CRPMobile/GetAllRequest',
    'ECRPActionUrl':BASE_URL + 'ess2/CRP/CRPMobile/ReleaseLetter',
    'getTotalLeaves':BASE_URL + 'ess2/Leave/Leave/GetNoofDays',
    'submitLeaveAction':BASE_URL + 'ess2/Leave/Leave/CreateLeaveAction',
    'getCDSUrl': BASE_URL + 'ess2/CDSServices/CDSServices/GetCDSPendingForApproval',
    'getCDSDetailUrl': BASE_URL + 'ess2/CDSServices/CDSServices/GetCDSDetails',
    'getCDSLineItemUrl': BASE_URL + 'ess2/CDSServices/CDSServices/GetAllCDSLineItems',
    'getCDSActionListUrl': BASE_URL + 'ess2/CDSServices/CDSServices/GetCDSUserActions',
    'getCDSActionSelectUrl': BASE_URL + 'ess2/CDSServices/CDSServices/GetCDSAuthorizedBody',
    'CDSActionUrl': BASE_URL + 'ess2/CDSServices/CDSServices/ActionTaken',
    'getExitUrl': BASE_URL + 'ess2//Ecc_Exit/ECCAPI/GetPendingRequest',
    'getSkillsUrl':BASE_URL + 'ess2/Ecc_Exit/ECCAPI/GetDropdownList',
    'getNoticePeriod':BASE_URL + 'ess2/Ecc_Exit/ECCAPI/Func_GetNoticePeriod',
    'ExitActionUrl': BASE_URL + 'ess2/Ecc_Exit/ECCAPI/SubmitRequest',
    'voucherHistoryUrl': BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/GetWorkflowHistory',
    'RRHistoryUrl': recruitmentPostDevUrl + 'RecruitmentHome/GetRRHistory',
    'loginWithAdToken':BASE_URL + 'ess2/CommonHandler/AuthenticateUserAppWithADToken',
    'leaveHistoryUrl': BASE_URL + 'ess2/Leave/Leave/GetHistory',
    'ECRPHistoryUrl': BASE_URL + 'ess2/CRP/CRPMobile/ViewLetterHistory',
    'exitHistoryUrl': BASE_URL + 'ess2//Ecc_Exit/ECCAPI/GetHistory',
    'visitingHistoryUrl': BASE_URL + 'ess2/VisitingCard/visitingCard/GetHistory',
    'CDSHistoryUrl': BASE_URL + 'ess2/CDSServices/CDSServices/History',
    'getAdvanceTravelUrl':BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/GetTRAdvanceDetailsWaitingForApproval',
    'advanceTravelActionUrl':BASE_URL + 'ess2/VoucherSystem/VouchersOnMobile/TRAddlAdvActions',
    'adLoginUrl':BASE_URL + 'ntlessnet/authentication/adauth.aspx',
    'adLogOut':AD_LOGOUT_BASE_URL + 'coforge.com/Home/SignOut',
    'getEESRecordUrl': BASE_URL + 'ess2/EES/Action/GetEESRecords',
    'saveAndSubmitEESUrl': BASE_URL + 'ess2/EES/Action/SaveUpdateESSRecords',
    'getITPendingRecords':ISD_BASE_URL + 'PendingforActionforMobileData',
    'approveITPendingRecords':ISD_BASE_URL + 'ApproveRecordsMobile',
    'itHistory':ISD_BASE_URL + 'WorkNoteHistory',
    'isdCreateRequestUrl': ISD_BASE_URL + 'CreateRequestForMobile',
    'isdGetServiceTypeUrl': ISD_BASE_URL + 'GetFiltersData',
    'getMyRequestsITDesk':ISD_BASE_URL + 'MyRequestforMobileData',
    'getITDeskSurveyQuestions':ISD_BASE_URL + 'GetSurveyQuestions',
    'submitSurveyQuestions':ISD_BASE_URL + 'SubmitSurveyQuestionsMobile',
    'isdSaveOrSubmitUrl': ISD_BASE_URL + 'SaveDataMobile',
    'isdFileUploadUrl': ISD_BASE_URL + 'FileUploadMobile',
    'isdMyRequestDetailsUrl': ISD_BASE_URL + 'GetRequestforMobileData',
    'autoCompleteEmployeeUrl': BASE_URL + 'ess2/HomePage/getData',
    'autoCompleteEmployeeNewUrl': BASE_URL + 'ess2/HomePage/getActiveData?',
    'isdRequestorUpdateUrl': ISD_BASE_URL + 'RequestorUpdate',
    'submitITAdditionalRemarks': ISD_BASE_URL + 'UpdateRemarkMobile',
    'deleteISDFile': ISD_BASE_URL + 'DeleteAttachments',
    'downloadISDFile': ISD_BASE_URL + 'DownloadAttachmentsMobile',
    'reOpenURL': BASE_URL + 'ess2/ISD/ISD/ReopenTicketForMobile',
    'myVouchers': VOUCHER_BASE_URL + 'GetAllDocuments',
    'cvEmployeeDetailsUrl': VOUCHER_OLD_BASE_URL + 'GetEmployeeDetail',
    'cvGetCategoryUrl': VOUCHER_BASE_URL + 'GetVoucherCategory',
    'cvGetExpenseTypeUrl': COMMON_VOUCHER_BASE_URL + 'UKVoucher/GetVoucherType',
    'cvGetMileageCommMilesUrl': COMMON_VOUCHER_BASE_URL + 'UKVoucher/GetCommMiles',
    'cvGetTravelLocationUrl': COMMON_VOUCHER_BASE_URL + 'UKVoucher/GetTrvelVoucherLocation',
    'cvGetTravelAmountUrl': COMMON_VOUCHER_BASE_URL + 'UKVoucher/GetUKTravelAmount',
    'cvGetCurrencyTypeUrl': COMMON_VOUCHER_BASE_URL + 'UKVoucher/GetCurrency',
    'cvGetSubCategoryUrl': VOUCHER_BASE_URL + 'GetVoucherSubCategory',
    'cvGetChildDetailsUrl': VOUCHER_BASE_URL + 'GetChildrenDetails',
    'cvGetClaimForUrl': VOUCHER_BASE_URL + 'GetClaimFor',
    'cvGetInvestmentPlanUrl': VOUCHER_BASE_URL + 'GetInvestmentPlan',
    'uploadVoucherAttachment': VOUCHER_BASE_URL + 'UploadDocument',
    'uploadVoucherAttachmentLTA': VOUCHER_BASE_URL + 'UploadLTADocument',
    'deleteVoucherAttachment': VOUCHER_BASE_URL + 'DeleteFiles',
    'downloadVoucherAttachment': VOUCHER_BASE_URL + 'DownloadDocumentForMobile',
    'cvGetWeddingDateUrl': VOUCHER_BASE_URL + 'GetWeddingDate',
    'cvGetTakeABreakBalanceUrl': VOUCHER_BASE_URL + 'GetBalanceDetails',
    'cvSaveAndSubmitUrl': VOUCHER_BASE_URL + 'SaveSubmitVoucherDetails',
    'cvGetLineItemDataUrl': VOUCHER_BASE_URL + 'GetLineItemData',
    'cvProjectSearchUrl': VOUCHER_BASE_URL + 'ProjectSearchResult',
    'cvSupervisorSearchUrl': VOUCHER_BASE_URL + 'SupervisorSearchResult',
    'cvDeleteLineItemUrl': VOUCHER_BASE_URL + 'DeleteLineItem',
    'cvDeleteVoucherUrl': VOUCHER_BASE_URL + 'DeleteVoucher',
    'cvFetchVDHBalance' : VOUCHER_BASE_URL + 'BindWelfareBalance',
    'cvHistoryUrl': VOUCHER_BASE_URL + 'VoucherHistory',
    'cvValidationUrl': VOUCHER_BASE_URL + 'ValidateCostCodeandProject',
    'fetchMobileBalance': VOUCHER_BASE_URL + 'MobileVoucherFormsDetails',
    'fetchPetrolBalance': VOUCHER_BASE_URL + 'PetrolVoucherBalance',
    'fetchDriverBalance': VOUCHER_BASE_URL + 'DriverVoucherBalance',
    'fetchMedicalBalance': VOUCHER_BASE_URL + 'MedicalBalance',
    'fetchCreateModifyStop': VOUCHER_BASE_URL + 'GetCreateModificationStopFlag',
    'fetchLtaBalance': VOUCHER_BASE_URL + 'LTABalanceAndClaimedVoucher',
    'downloadCertificate': BASE_URL + 'ess2/Misc/CommonHandler/GetCertificate',
    'policySchemes': BASE_URL + 'ess2/Misc/CommonHandler/GetPolicy',
    'policyPDF': BASE_URL + 'ess2//Misc/CommonHandler/DownloadPolicy',
    'getUSExpenseTypes': BASE_URL + 'ess2/VoucherSystem/ActionHandler/UsVoucherExpenseType',
    'getUSLCVModeRate': BASE_URL + 'ess2/VoucherSystem/ActionHandler/UsVoucherLCVModeRate',
    'fetchProjectListUrl': BASE_URL + 'ess2/VoucherSystem/ActionHandler/VoucherProjectCode',
    'getISD_SurveyQuestion':BASE_URL + 'ess2/ISD/ISD/GetSurveyQuestions',
    'submitISDSurvey':BASE_URL + 'ess2/ISD/ISD/SubmitSurveyQuestions',
    'getInputControls':BASE_URL + 'ess2/Timesheet/TimesheetHandler/BindControls',
    'getDayTypes':BASE_URL + 'ess2/Timesheet/TimesheetHandler/GetMyTimesheetList',
    'getRecords':BASE_URL + 'ess2/Timesheet/TimesheetHandler/GetEmployeeTimesheetData',
    'fetchTimesheetWeekList': TIMESHEET_BASE_URL + 'BindControls',
    'fetchTimesheetEmpDetails': TIMESHEET_BASE_URL + 'GetEmpDetails',
    'fetchTimesheetMyWeekList': TIMESHEET_BASE_URL + 'GetMyTimesheetList',
    'fetchSupervisorList':TIMESHEET_BASE_URL + 'GetSVPNameList',
    'getLineItemHistory':TIMESHEET_BASE_URL + 'GetHistory',
    'saveSubmitTimeSheet':TIMESHEET_BASE_URL + 'SubmitTimesheetDetails',
    'saveSubmitTimeSheetByApprover':TIMESHEET_BASE_URL + 'SubmitTimesheetDetailsbyApprover',
    'deleteTimeSheetRecord':TIMESHEET_BASE_URL + 'DeleteRecords',
    'fetchTimeSheetApprovals':TIMESHEET_BASE_URL + 'TimesheetApprovalList',
    'fetchApproverTimeSheetData':TIMESHEET_BASE_URL + 'GetApproverTimesheetData',
    'idCard':BASE_URL + 'ess2/ICard/ICardHandler/ICardDownloadApi',


    'getHREmpDetails':BASE_URL + 'ess2/HRDesk/HRDesk/GetEmployeeDetails',
    'getHRCategory':BASE_URL + 'ess2/HRDesk/HRDesk/BindCategory',
    'getHRSubCategory':BASE_URL + 'ess2/HRDesk/HRDesk/BindSubCategory',
    'getHrMyList':BASE_URL + 'ess2/HRDesk/HRDesk/GetMyQueryList',
    'getMyTicketDetail':BASE_URL + 'ess2/HRDesk/HRDesk/GetQuery',
    'getHrSlaDetails':BASE_URL + 'ess2/HRDesk/HRDesk/GetSLADetails',
    'getHrActivities':BASE_URL + 'ess2/HRDesk/HRDesk/GetActivities',
    'submitHrData':BASE_URL + 'ess2/HRDesk/HRDesk/SubmitQuery',
    'submitByHrData':BASE_URL + 'ess2/HRDesk/HRDesk/SubmitQuerybyHR',
    'hrSurveyQuestions':BASE_URL + 'ess2/HRDesk/HRDesk/GetSurveyQuestions',
    'submitHrSurvey':BASE_URL + 'ess2/HRDesk/HRDesk/SubmitSurveyQuestionsmobile',
    'getHrFiles':BASE_URL + 'ess2/HRDesk/HRDesk/GetFilesDetails',
    'deleteHrFile':BASE_URL + 'ess2/HRDesk/HRDesk/DeleteAttachments',
    'downloadHrFile':BASE_URL + 'ess2/HRDesk/HRDesk/DownloadAttachments',
    'uploadHrFile': BASE_URL + 'ess2/HRDesk/HRDesk/FileUpload',
};
