
import Config from '../config/index';
const BASE_URL = Config.api.host;
const CAREER_BASE_URL = Config.api.careerHost;
const AD_LOGOUT_BASE_URL = Config.api.adLogOut;
const initialURL = `${BASE_URL}ntlessnet/webservices/`;
const recruitmentURL = CAREER_BASE_URL + 'RecruitmentQA/Recruitment/';
const recruitmentPostDevUrl = CAREER_BASE_URL + 'Careers/Recruitment/';
const ISD_BASE_URL = `${BASE_URL}ess2/ISD/ISD/`;
const COMMON_VOUCHER_BASE_URL = `${BASE_URL}ess2/VoucherSystem/`;
const VOUCHER_BASE_URL =`${BASE_URL}ess2/VoucherSystem/ActionHandler/`;
const VOUCHER_OLD_BASE_URL = `${BASE_URL}ess2/VoucherSystem/ActionHandler/`;
const TIMESHEET_BASE_URL = `${BASE_URL}ess2/Timesheet/TimesheetHandler/`;
const VOUCHER_ON_MOBILE =  `${BASE_URL}ess2/VoucherSystem/VouchersOnMobile/`;
const HR_DESK= `${BASE_URL}ess2/HRDesk/HRDesk/`;
const MY_INFO = `${BASE_URL}ess2/misc/Myinfo/`;
const CDS_SERVICES = `${BASE_URL}ess2/CDSServices/CDSServices/`;
const VISA_SERVICES = `${BASE_URL}ess2/Visa/VisaHandler/`;
const LEAVE_SERVICES = `${BASE_URL}ess2/Leave/Leave/`;
const ECRP_SERVICES = `${BASE_URL}ess2/CRP/CRPMobile/`;
const ECC_EXIT_SERVICES = `${BASE_URL}ess2/Ecc_Exit/ECCAPI/`;
const VISITING_SERVICES =`${BASE_URL}ess2/VisitingCard/VisitingCard/`;
const EES_RECORDS_SERVICES =`${BASE_URL}ess2/EES/Action/`
export default {
    'isDevEnvironment': BASE_URL.includes('dev') ? true : false,
    'checkEligibility':BASE_URL + 'ess2/Misc/Attendence/ViewAttendence',
    'checkAttendance':BASE_URL + 'ess2/Misc/Attendence/MarkAttendenceMobile',
    'getAppVersion':BASE_URL + 'ess2/CommonHandler/GetAppVersion',
    'loginUrl': initialURL + 'Authentication.asmx/AuthenticateUser?',
    'loginNewUrl': initialURL + 'Authentication.asmx/AuthenticateUserapp?',
    'loginNewUrl2': BASE_URL + 'ess2/CommonHandler/AuthenticateUserAppWithToken',
    'pendingRequestUrl': recruitmentURL + 'RecruitmentHome/GetPendingForApproval?',
    'getSupervisorListUrl': recruitmentURL + 'Common/GetRequestorBasedonparam?',
    'updateRequestStatusUrl': recruitmentURL + 'Request/UpdateStatus?',
    'pendingRequestPostURL': recruitmentPostDevUrl + 'RecruitmentHome/GetPendingForApproval?',
    'getPendingDashboardCountUrl': BASE_URL + 'ess2/misc/WebAPI/GetPendingCount',
    'getRequestorListUrl': recruitmentPostDevUrl + 'Common/GetRequestorBasedonparam?',
    'voucherActionUrl':`${VOUCHER_ON_MOBILE}VoucherAction`,
    'RRActionUrl': recruitmentPostDevUrl + 'Request/UpdateRequestStatus',
    'getLCVoucherUrl':`${VOUCHER_ON_MOBILE}GetLCVVoucherDetails`,
     'getCSHVoucherUrl': `${VOUCHER_ON_MOBILE}GetCSHVoucherDetails`,
    'pendingVoucherPostURL' :`${VOUCHER_ON_MOBILE}GetVouchersPendingForApproval`,
    'fetchSuperVisorListUrl': CAREER_BASE_URL + 'Careers/Recruitment/Common/GetRequestorBasedonparam?', //all employee data
    'cancelActionUrl':`${VOUCHER_ON_MOBILE}VoucherAction`,
    'approveActionUrl': CAREER_BASE_URL + 'Careers/Recruitment/Request/UpdateRequestStatus',
    'getCshVouchers':`${VOUCHER_ON_MOBILE}GetCSHVoucherDetails`,
    'getLcvVouchers':`${VOUCHER_ON_MOBILE}GetLCVVoucherDetails`,
    'getTrPendingList':`${VOUCHER_ON_MOBILE}GetTRPendingForApproval`,
    'trActions':`${VOUCHER_ON_MOBILE}TRActions`,
    'getTrApproverList':`${VOUCHER_ON_MOBILE}GetApproversList`,
    'getHRCommunication':`${MY_INFO}HRCommunication`,
    'getGratuityDetails':`${MY_INFO}GetBalances`,
    'addressInfoUrl' : `${MY_INFO}GetAddressDetailsSap`,
    'getFamily':`${MY_INFO}GetFamilyDetailsSap`,
    'getYearLocation':`${MY_INFO}GetYearNCountry`,
    'getHolidays':`${MY_INFO}GetHolidayList`,
    'getLeaves':`${LEAVE_SERVICES}GetPendingLeaveList`,
    'submitLeaveRequest':`${LEAVE_SERVICES}LeaveAction`,
    'usVoucherActionUrl':`${VOUCHER_ON_MOBILE}USVoucherActions`,
    'getVisaUrl':`${VISA_SERVICES}GetMyTask`,
    'visaActionUrl': `${VISA_SERVICES}submitVisaDetails`,
    'visaHistoryUrl': `${VISA_SERVICES}GetHistory`,
    'getVisitingUrl': `${VISITING_SERVICES}GetAllRequest`,
    'visitingActionUrl': `${VISITING_SERVICES}UpdateVisitingCardRequest`,
    'fetchSupervisorVisaUrl' : `${VISA_SERVICES}SearchEmpData`,
    'createLeave':`${LEAVE_SERVICES}LeaveBalances`,
    'getECRPUrl': `${ECRP_SERVICES}GetAllRequest`,
    'ECRPActionUrl':`${ECRP_SERVICES}ReleaseLetter`,
    'getTotalLeaves':`${LEAVE_SERVICES}GetNoofDays`,
    'submitLeaveAction':`${LEAVE_SERVICES}CreateLeaveAction`,
    'getCDSUrl': `${CDS_SERVICES}GetCDSPendingForApproval`,
    'getCDSDetailUrl': `${CDS_SERVICES}GetCDSDetails`,
    'getCDSLineItemUrl': `${CDS_SERVICES}GetAllCDSLineItems`,
    'getCDSActionListUrl': `${CDS_SERVICES}GetCDSUserActions`,
    'getCDSActionSelectUrl': `${CDS_SERVICES}GetCDSAuthorizedBody`,
    'CDSActionUrl': `${CDS_SERVICES}ActionTaken`,
    'getExitUrl': BASE_URL + 'ess2//Ecc_Exit/ECCAPI/GetPendingRequest',
    'getSkillsUrl':`${ECC_EXIT_SERVICES}GetDropdownList`,
    'getNoticePeriod':`${ECC_EXIT_SERVICES}Func_GetNoticePeriod`,
    'ExitActionUrl': `${ECC_EXIT_SERVICES}SubmitRequest`,
    'voucherHistoryUrl': `${VOUCHER_ON_MOBILE}GetWorkflowHistory`,
    'RRHistoryUrl': recruitmentPostDevUrl + 'RecruitmentHome/GetRRHistory',
    'loginWithAdToken':BASE_URL + 'ess2/CommonHandler/AuthenticateUserAppWithADToken',
    'leaveHistoryUrl': `${LEAVE_SERVICES}GetHistory`,
    'ECRPHistoryUrl':`${ECRP_SERVICES}ViewLetterHistory`,
    'exitHistoryUrl': BASE_URL + 'ess2//Ecc_Exit/ECCAPI/GetHistory',
    'visitingHistoryUrl': `${VISITING_SERVICES}GetHistory`,
    'CDSHistoryUrl': `${CDS_SERVICES}History`,
    'getAdvanceTravelUrl':`${VOUCHER_ON_MOBILE}GetTRAdvanceDetailsWaitingForApproval`,
    'advanceTravelActionUrl':`${VOUCHER_ON_MOBILE}TRAddlAdvActions`,
    'adLoginUrl':BASE_URL + 'ntlessnet/authentication/adauth.aspx',
    'adLogOut':AD_LOGOUT_BASE_URL + 'coforge.com/Home/SignOut',
    'getEESRecordUrl': `${EES_RECORDS_SERVICES}GetEESRecords`,
    'saveAndSubmitEESUrl': `${EES_RECORDS_SERVICES}SaveUpdateESSRecords`,
    'getITPendingRecords':`${ISD_BASE_URL}PendingforActionforMobileData`,
    'approveITPendingRecords':`${ISD_BASE_URL}ApproveRecordsMobile`,
    'itHistory':`${ISD_BASE_URL}WorkNoteHistory`,
    'isdCreateRequestUrl':`${ISD_BASE_URL}CreateRequestForMobile`,
    'isdGetServiceTypeUrl': `${ISD_BASE_URL}GetFiltersData`,
    'getMyRequestsITDesk':`${ISD_BASE_URL}MyRequestforMobileData`,
    'getITDeskSurveyQuestions':`${ISD_BASE_URL}GetSurveyQuestions`,
    'submitSurveyQuestions':`${ISD_BASE_URL}SubmitSurveyQuestionsMobile`,
    'isdSaveOrSubmitUrl': `${ISD_BASE_URL}SaveDataMobile`,
    'isdFileUploadUrl': `${ISD_BASE_URL}FileUploadMobile`,
    'isdMyRequestDetailsUrl': `${ISD_BASE_URL}GetRequestforMobileData`,
    'autoCompleteEmployeeUrl': BASE_URL + 'ess2/HomePage/getData',
    'autoCompleteEmployeeNewUrl': BASE_URL + 'ess2/HomePage/getActiveData?',
    'isdRequestorUpdateUrl': `${ISD_BASE_URL}RequestorUpdate`,
    'submitITAdditionalRemarks': `${ISD_BASE_URL}UpdateRemarkMobile`,
    'deleteISDFile': `${ISD_BASE_URL}DeleteAttachments`,
    'downloadISDFile': `${ISD_BASE_URL}DownloadAttachmentsMobile`,
    'reOpenURL': `${ISD_BASE_URL}ReopenTicketForMobile`,
    'myVouchers': `${VOUCHER_BASE_URL}GetAllDocuments`,
    'cvEmployeeDetailsUrl': VOUCHER_OLD_BASE_URL + 'GetEmployeeDetail',
    'cvGetCategoryUrl': `${VOUCHER_BASE_URL}GetVoucherCategory`,
    'cvGetExpenseTypeUrl': COMMON_VOUCHER_BASE_URL + 'UKVoucher/GetVoucherType',
    'cvGetMileageCommMilesUrl': COMMON_VOUCHER_BASE_URL + 'UKVoucher/GetCommMiles',
    'cvGetTravelLocationUrl': COMMON_VOUCHER_BASE_URL + 'UKVoucher/GetTrvelVoucherLocation',
    'cvGetTravelAmountUrl': COMMON_VOUCHER_BASE_URL + 'UKVoucher/GetUKTravelAmount',
    'cvGetCurrencyTypeUrl': COMMON_VOUCHER_BASE_URL + 'UKVoucher/GetCurrency',
    'cvGetSubCategoryUrl': `${VOUCHER_BASE_URL}GetVoucherSubCategory`,
    'cvGetChildDetailsUrl': `${VOUCHER_BASE_URL}GetChildrenDetails`,
    'cvGetClaimForUrl':`${VOUCHER_BASE_URL}GetClaimFor`,
    'cvGetInvestmentPlanUrl':`${VOUCHER_BASE_URL}GetInvestmentPlan`,
    'uploadVoucherAttachment':`${VOUCHER_BASE_URL}UploadDocument`,
    'uploadVoucherAttachmentLTA':`${VOUCHER_BASE_URL}UploadLTADocument`,
    'deleteVoucherAttachment':`${VOUCHER_BASE_URL}DeleteFiles`,
    'downloadVoucherAttachment':`${VOUCHER_BASE_URL}DownloadDocumentForMobile`,
    'cvGetWeddingDateUrl':`${VOUCHER_BASE_URL}GetWeddingDate`,
    'cvGetTakeABreakBalanceUrl':`${VOUCHER_BASE_URL}GetBalanceDetails`,
    'cvSaveAndSubmitUrl':`${VOUCHER_BASE_URL}SaveSubmitVoucherDetails`,
    'cvGetLineItemDataUrl':`${VOUCHER_BASE_URL}GetLineItemData`,
    'cvProjectSearchUrl':`${VOUCHER_BASE_URL}ProjectSearchResult`,
    'cvSupervisorSearchUrl':`${VOUCHER_BASE_URL}SupervisorSearchResult`,
    'cvDeleteLineItemUrl':`${VOUCHER_BASE_URL}DeleteLineItem`,
    'cvDeleteVoucherUrl':`${VOUCHER_BASE_URL}DeleteVoucher`,
    'cvFetchVDHBalance' :`${VOUCHER_BASE_URL}BindWelfareBalance`,
    'cvHistoryUrl':`${VOUCHER_BASE_URL}VoucherHistory`,
    'cvValidationUrl':`${VOUCHER_BASE_URL}ValidateCostCodeandProject`,
    'fetchMobileBalance':`${VOUCHER_BASE_URL}MobileVoucherFormsDetails`,
    'fetchPetrolBalance':`${VOUCHER_BASE_URL}PetrolVoucherBalance`,
    'fetchDriverBalance':`${VOUCHER_BASE_URL}DriverVoucherBalance`,
    'fetchMedicalBalance':`${VOUCHER_BASE_URL}MedicalBalance`,
    'fetchCreateModifyStop':`${VOUCHER_BASE_URL}GetCreateModificationStopFlag`,
    'fetchLtaBalance':`${VOUCHER_BASE_URL}LTABalanceAndClaimedVoucher`,
    'downloadCertificate': BASE_URL + 'ess2/Misc/CommonHandler/GetCertificate',
    'policySchemes': BASE_URL + 'ess2/Misc/CommonHandler/GetPolicy',
    'policyPDF': BASE_URL + 'ess2//Misc/CommonHandler/DownloadPolicy',
    'getUSExpenseTypes': `${VOUCHER_BASE_URL}UsVoucherExpenseType`,
    'getUSLCVModeRate': `${VOUCHER_BASE_URL}UsVoucherLCVModeRate`,
    'fetchProjectListUrl':`${VOUCHER_BASE_URL}VoucherProjectCode`,
    'getISD_SurveyQuestion':`${ISD_BASE_URL}GetSurveyQuestions`,
    'submitISDSurvey':`${ISD_BASE_URL}SubmitSurveyQuestions`,
    'getInputControls':`${TIMESHEET_BASE_URL}BindControls`,
    'getDayTypes':`${TIMESHEET_BASE_URL}GetMyTimesheetList`,
    'getRecords':`${TIMESHEET_BASE_URL}GetEmployeeTimesheetData`,
    'fetchTimesheetWeekList': `${TIMESHEET_BASE_URL}BindControls`,
    'fetchTimesheetEmpDetails':`${TIMESHEET_BASE_URL}GetEmpDetails`,
    'fetchTimesheetMyWeekList':`${TIMESHEET_BASE_URL}GetMyTimesheetList`,
    'fetchSupervisorList':`${TIMESHEET_BASE_URL}GetSVPNameList`,
    'getLineItemHistory':`${TIMESHEET_BASE_URL}GetHistory`,
    'saveSubmitTimeSheet':`${TIMESHEET_BASE_URL}SubmitTimesheetDetails`,
    'saveSubmitTimeSheetByApprover':`${TIMESHEET_BASE_URL}SubmitTimesheetDetailsbyApprover`,
    'deleteTimeSheetRecord':`${TIMESHEET_BASE_URL}DeleteRecords`,
    'fetchTimeSheetApprovals':`${TIMESHEET_BASE_URL}TimesheetApprovalList`,
    'fetchApproverTimeSheetData':`${TIMESHEET_BASE_URL}GetApproverTimesheetData`,
    'idCard':BASE_URL + 'ess2/ICard/ICardHandler/ICardDownloadApi',
    'getHREmpDetails':`${HR_DESK}GetEmployeeDetails`,
    'getHRCategory':`${HR_DESK}BindCategory`,
    'getHRSubCategory':`${HR_DESK}BindSubCategory`,
    'getHrMyList':`${HR_DESK}GetMyQueryList`,
    'getMyTicketDetail':`${HR_DESK}GetQuery`,
    'getHrSlaDetails':`${HR_DESK}GetSLADetails`,
    'getHrActivities':`${HR_DESK}GetActivities`,
    'submitHrData':`${HR_DESK}SubmitQuery`,
    'submitByHrData':`${HR_DESK}SubmitQuerybyHR`,
    'hrSurveyQuestions':`${HR_DESK}GetSurveyQuestions`,
    'submitHrSurvey':`${HR_DESK}SubmitSurveyQuestionsmobile`,
    'getHrFiles':`${HR_DESK}GetFilesDetails`,
    'deleteHrFile':`${HR_DESK}DeleteAttachments`,
    'downloadHrFile':`${HR_DESK}DownloadAttachments`,
    'uploadHrFile': `${HR_DESK}FileUpload`,
};
