export const IT_DESK_LOADING = "it_desk_loading";
export const IT_DESK_ERROR = "it_desk_error";
export const IT_DESK_DATA = "it_desk_data";
export const IT_DESK_HISTORY_DATA = "it_desk_history_data";
export const IT_DESK_ACTION_DATA = "it_desk_action_data";
export const RESET_IT_DESK = "reset_it_desk";
export const UNCHECKED_ICON = require('../../../assets/unchecked_icon.jpeg');
export const CHECKED_ICON = require('../../../assets/checked_icon.jpeg');
export const BUTTON_OPTIONS = ["Approve","Reject"];
export const REQUEST_SUCCESS = "Your request has been submitted successfully."
