import { StyleSheet } from 'react-native';
import { moderateScale } from '../../components/fontScaling.js';
var appConfig = require('../../../appconfig');
export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  buttonContainer:{
    flexDirection:'row',
    justifyContent:'space-between',
  },
scrollViewStyle:{
  paddingVertical: moderateScale(2),
  height:'75%',
},
buttonText:{
  fontSize: 20,
  textAlign: 'center',
  color:'#fff',
},
textContainer:{flexDirection:'row',justifyContent:'space-around'},
heading:{fontWeight:'bold',flex:1},
value:{flex:1},
approveButton:{
  backgroundColor:appConfig.DARK_BLUISH_COLOR,
  paddingTop:moderateScale(13),
  paddingBottom:moderateScale(13),
  width:'50%',
  alignItems:'center',
  borderRadius:moderateScale(5),
  marginLeft:moderateScale(-3),
},
rejectButton:{
  backgroundColor:appConfig.INVALID_BUTTON_COLOR,
  paddingTop:moderateScale(13),
  paddingBottom:moderateScale(13),
  width:'50%',
  alignItems:'center',
  borderRadius:moderateScale(5),
  marginRight:moderateScale(-3),
},
buttonTextColor:{
  color:'#fff',
},
bottomButtonContainer:{
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-around',
    marginTop: '2%',
},
cardBackground: {
  borderWidth: 1,
         borderColor: appConfig.FIELD_BORDER_COLOR,
        flex: 1,
         backgroundColor: '#fff',
         borderRadius: 5,
         shadowOffset:{  width: 10,  height: 10  },
         shadowColor: 'black',
         padding:10,
},
dropDownContainer:{
  flexDirection:'row',
  alignItems: 'center',
  justifyContent:'space-around',
  paddingHorizontal: 15,
},
pickerBox:{
  width:'60%',
  alignItems:'center',
  padding:10,
},
dropIcon:{
  flexDirection:'row',
  borderWidth:1,
  backgroundColor: '#DBE9f3',
  borderRadius:5,
  borderColor:appConfig.APP_ORANGE,
},
pickerObject1:{
  width:'100%',
},
pickerTextStyle:{
  fontSize: 20,
  textAlign: 'center',
  color:'#000',
},
gradientStyle:{
  padding:15,
  marginTop:15,
  width:'95%',
  alignSelf:'center',
  borderWidth:1,
  borderColor:'grey',
  borderRadius:5,
},
dropdownStyle:{
  height:'20%',
  alignItems:'flex-start',
  borderWidth:1,
  borderColor:appConfig.APP_ORANGE,
  // position:'absolute',
  // top:0,
  // right:0,
  // bottom:0,
  // left:0,

},
dropdownTextStyle:{
  fontSize: 16,
  textAlign: 'center',
  paddingHorizontal:'15%',
  color:'#000',
},
  listOuterView: {
    paddingHorizontal: moderateScale(16),
    paddingBottom: moderateScale(160),
  },
  searchBar: {
    backgroundColor: '#FFFFFF',
    width: '90%',
    marginLeft: moderateScale(16),
  },
  listItem:{
    marginLeft: moderateScale(16),
    width: '90%',
    paddingTop: 10,
    paddingBottom: 10,
  },
  listText:{fontSize:20},
  supervisorSeparator:{marginTop: 10,
    height: 0.5,
    backgroundColor: appConfig.LIST_BORDER_COLOUR,
  },
  selectedSupervisor:{
    alignItems:'center',
    alignSelf:'flex-end',
    marginRight:10,
    width:'60%',
  },
  textSupervisor:{
    fontSize:16,
    paddingTop:10,
    paddingBottom:10,
  },
  canButtonText:{
    fontSize:16,
    paddingTop:10,
    paddingBottom:10,
    color:'#fff',
  },
  btnSupervisorText:{
    color:'#fff',
    fontSize:16,
    paddingTop:10,
    paddingBottom:10,
  },
  remarksParent:{
		borderWidth: 1,
		borderColor: appConfig.LIST_BORDER_COLOUR,
		borderRadius: moderateScale(5),
		width: '95%',
		alignItems: 'center',
		alignSelf: 'center',
		marginTop: moderateScale(20),
  },
  textInputStyle:{
    width: '100%',
    paddingLeft: 10,
    paddingTop: 10,
    paddingBottom: 10,
    color: 'black',
  },
  submitButton:{
    borderWidth: 1,
		borderColor: appConfig.LIST_BORDER_COLOUR,
		borderRadius: moderateScale(5),
    width: '95%',
    alignItems: 'center',
		alignSelf: 'center',
    marginTop: moderateScale(20),
    backgroundColor:appConfig.VALID_BORDER_COLOR,
  },
  rejectContainer:{
    flexDirection:'row',
    justifyContent:'space-between',
    marginLeft:10,
    marginRight:10,
    marginTop:20,
  },
  historyViewStyle: {
    marginVertical: 2,
    alignSelf: 'flex-start',
  },
  negativeButton:{
    borderWidth: 1,
		borderColor: appConfig.LIST_BORDER_COLOUR,
		borderRadius: moderateScale(5),
    width:'48%',
    alignItems: 'center',
		alignSelf: 'center',
    marginTop: moderateScale(20),
    backgroundColor:appConfig.INVALID_BUTTON_COLOR,
  },
  modalTextStyle:{marginHorizontal: '4.3%',
  fontSize: moderateScale(14),
  color: appConfig.GUN_METAL_COLOR,
  letterSpacing: moderateScale(0.7),
  textAlign: 'center',
},
});
